# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 207392f96f7efd80e8f063fe119d1c639ad227d10681c077983d8634ef17c455e41829ea2344c36b5ed76df3f235ac0c732515abea1765e621ec269ae2540fcf

test:
  secret_key_base: 2427dd05e6dd2d0bd91c62303d995a271cbb6655f3293a7b46f2b980100cde188fb6c3a667d57947c73f65a807e9f7aa1d8149dcf302e9e40147f520c6fc233b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
